:sectanchors:
:toc:
:toclevels: 3
:icons: font
:iconfont-cdn: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/fontawesome.min.css

= Sortier

This tool is capable to sort any kind of tv shows.
During the process, all video files will be renamed, sorted into folders named after the season they’re belonging to and saved wherever you desire.
By that it is possible to upload the files to your media server like Plex or Emby.
These media centers need the correct naming convention in order to find all the metadata like posters, background images and other information.

The seasons need to be in a folder called after the season. F.e.: `Season 01`

Also, the videos itself need to follow these kind of conventions.
Files need to be named like this:

`My New Show (2011) s01e01.mkv.`

This very tool does all that for you.

=== Installation

To install Sortier just copy the following line to your Terminal or command line:

`pip3 install git+https://github.com/michaelgrossklos/sortier.git`

I assume you have Python >= 3.7 already installed on your machine.
If not, go to https://www.python.org/ and follow the instructions there.

=== Usage

==== Help

First of all, it is important to know, that you always can use the
`--help` option.
This will print someting like this:

....
Usage: sortier [OPTIONS] COMMAND [ARGS]...

  Sorting your ripped or downloaded tv-shows into folders named after the
  seasons they're belonging to (f.e.: Season 01). Renames all files like
  "Name Of Show s01e01.ext" for direct use in your media center like Plex or
  Emby. So it can find all meta data needed.

Options:
  -l, --language TEXT       Sets the language for season names
  --debug / --no-debug      Turn debug mode on
  --delete-folders BOOLEAN  Delete the source folder after copying the file
  --help                    Show this message and exit.

Commands:
  addextensions  Extends the list of file extensions.
  destpath       Changes the destination path permanently
  oripath        Changes the origin path permanently
  settings       Shows the actual settings
  titles         The titles of the shows to be sorted.

....

As you can see in the first line, you first (and always) need to call the program itself by using `sortier`.
After that you can specify options which usually begins with `--` (two dashes).
Or (in some cases) also with just one `-`.
This is just the short hand version of it.
The effect will be exactly the same.

For example `-l` is the same as `--language`.

All options are, well… optional ;)

Some of them requiring arguments to be passed in, some do not.
`--delete-folders` for example is one that does not need any arguments.
Whereas `--origin-path` in fact needs the path where all the video files are located.

On the other hand, there are commands.
Those need to be typed after the options (if you’ve specified one).
Some of them are requiring arguments.
Some do not.
For Example `settings` does not need any argument.
If you set one, you would get an error.

A complete line for using Sortier could look something like this:

`sortier -l=en --delete-folders titles "my first show" "my second show"`
or

`sortier titles "my fisrt show" "my second show"` if you wouldn’t use any options.

IMPORTANT: Important to know is, that you can’t use two commands at the same time, whereas you are able to use more than one option at ones.
The order in which you specify the options does not matter.

== Commands

'''
=== Renaming files

The files to be renamed are only the video files that get stored into the destination folder.

==== File name a.k.a tv-show titles (required)

In order to rename - and more importantly - find the right files, you need to provide the titles of the show.

You do that by typing `sortier titles "My tv show 1" "My tv show 2"`.
Capitalization will be ignored.
Notice, that you are able to specify just one, or an unlimited amount of titles.
You just need to wrap each title into quotation marks followed by a space.
The order in which you define the titles is irrelevant.

This also means, that you can have multiple tv shows including multiple seasons in your source folder.
As long as each episode is contained in its own folder and this folder is somehow named after the show.
For example: `my.tv.show.1` or `345-my.tv.show_2` or `dim-mytvshow.3-IFRIM`.
The characters in between the words of the title itself, and surrounding it are not relevant at all.
Sortier will find the title anyways.

How the video file itself is named, does not matter, as long as it holds the season and episode count.
For example `my.first.show.s01e20`.
In which `s01e20` means season 1, episode 20. Without that, Sortier is incapable of sorting the episodes and will stop running with printing out an error message.

'''

=== File extensions

Not always, but most of the time, are the provided default file extensions sufficient.
If that is not the case you can extend the list of file extensions by using the commmand
`sortier addextensions ".mpeg" ".webm"`.

Like the command title, you can specify just one or an unlimited amount of extensions.
You just need to wrap each extension into quotation marks followed by a space.
The order in which you define those, is irrelevant.

The extension you’re adding, will get saved permanently.
So, you don’t need to set them the next time you use Sortier.

If you want to know what extensions are already provided, just use the command `sortier settings` without any arguments, and an overview of all settings gets printed on the screen.

'''

=== Show all settings

As you are able to change most of the settings, you need to know the actual state they’re in.
Just type `sortier settings` without any arguments, and something like the following will get printed on the screen:

[source,bazaar]
----
ACTUAL SETTINGS FOR SORTIER:
Regex for seasons: (s([0-9]{2})e[0-9]{2})
Origin/Source path: Downloads/extracted
Destination path: Downloads/extracted/SORTED
File extensions available: ['.mkv', '.avi', '.mp4', '.mov']
Languages available: ['de', 'en', 'es', 'fr', 'it', 'ru']
Language set: en
Season is called: Season

You can find more information on:
https://github.com/michaelgrossklos/sortier
----

=== Setting the paths

There are two paths to be set.
The origin path and the destination path.

==== Origin/Source path

This is the path where the ripped or downloaded files are to find at.
In the settings you’ll see the whole path.
Which by default is set to
`Downloads/extracted`.

That is the relative path (from the home directory) to your source folder, where all the files are in.
You can set this path to any location under your home directory, as long as one won’t need administrator rights to read from it.
Most of the time, it will be your downloads folder or any subfolders beneath it.
You just need to provide the parent folder, where all other folders, that containing the video files are contained in.

In the example above, your folder structure would look something like this (assuming you’re on Mac OSX):

....
└── Users/
    └── <user name>/
        └── Downloads/
            └── extracted/
                ├── The.Show.S02E01.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA/
                │   └── The.Show.S02E01.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA.mkv
                ├── The.Show.S02E02.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA/
                │   └── The.Show.S02E02.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA.mkv
                ├── The.Show.S02E03.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA/
                │   └── The.Show.S02E03.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA.mkv
                ├── Another.Show.S02E01.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA/
                │   └── Another.Show.S02E01.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA.mkv
                ├── Another.Show.S02E02.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA/
                │   └── Another.Show.S02E02.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA.mkv
                ├── ...└── Another.Show.S02E02.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA.mkv
....

In which `extracted` is the parent folder of all the video files.

==== Destination path

All the video files will be copied to this path.

This path by default is set to
`<your home directory>/Downloads/extracted/SORTED`.
It’s the same principal as of the origin path.

As mentioned above, the files will be sorted into folders named after the show and subfolders named after the seasons.
This could look something like this:

....
└── Users/
    └── <user name>/
        └── Downloads/
            └── extracted/
                ├── The.Show.S02E01.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA/
                │   └── The.Show.S02E01.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA.mkv
                ├── The.Show.S02E02.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA/
                │   └── The.Show.S02E02.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA.mkv
                ├── The.Show.S02E03.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA/
                │   └── The.Show.S02E03.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA.mkv
                ├── Another.Show.S02E01.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA/
                │   └── Another.Show.S02E01.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA.mkv
                ├── Another.Show.S02E02.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA/
                │   └── Another.Show.S02E02.COMPLETE.English.DL.720p.BluRay.x264-UTOPiA.mkv
                ├── ...
                └── SORTED/
                    ├── The Show/
                    │   ├── Season 01/
                    │   │   ├── The Show s01e01.mkv
                    │   │   ├── The Show s01e02.mkv
                    │   │   ├── The Show s01e03.mkv
                    │   │   └── ...
                    │   └── Season 02/
                    │       ├── The Show s02e01.mkv
                    │       ├── The Show s02e02.mkv
                    │       ├── The Show s02e03.mkv
                    │       └── ...
                    └── Another Show/
                        └── Season 02/
                            ├── Another s02e01.mkv
                            ├── Another s02e02.mkv
                            └── ...
....

== Options

=== Language

If you set the language, it really is not much what changes.
The only thing that changes is how the folder for the seasons gets named.
In english it will be `Season`.
In German `Staffel` and in french `Saison` and so on.
You can set the language by eather use the long or the short version of this option.

`--language en` or `-l en`

The default is German.

These are the languages available:

- en => English => Season
- de => German => Staffel
- fr => French => Saison
- it => Italian => Stagione
- ru => Russian => Sezon
- es => Spanish => Temporada

TIP: Actually, there is no functionality to permanently set the language.
So you have to use it every time you use Sortier.

== Flags

Flags are a kind of options.
The difference is, that these don't receive any arguments like options do.
You just use the flag like so `--flag`

=== Delete folders

If you use the flag `--delete-folders` without any arguments, all source folders will get deleted.

[WARNING]
Use this functionality with caution.

=== Debug mode

Sometimes one needs to debug.
Users usually do not need this mode.
You can use `--debug` every time you want the debug mode to be switched on.

What it does is very simple.
During the execution of Sortier, you will see some messages on the command line.
These are giving some hints what the program actually does.

== Configuration file

During the installation Sortier saves a small configuration file.
The file format is JSON and very easy to understand.

This is what it looks like initally:

[source,json]
....
{
  "default_paths": {
    "ORIGIN_PATH": "Downloads/extracted",
    "DESTINATION_PATH": "Downloads/extracted/SORTED"
  },
  "FILE_EXTENSIONS": [
    ".mkv",
    ".avi",
    ".mp4",
    ".mov"
  ],
  "LANGUAGES": {
    "de": "Staffel",
    "en": "Season",
    "es": "Temporada",
    "fr": "Saison",
    "it": "Stagione",
    "ru": "Sezon"
  },
  "REGEX": "(s([0-9]{2})e[0-9]{2})"
}
....

The default installallation path is: `<users home directory>/.config/sortier/sortier.json`.
Where `<users home directory>` gets substituted with the path to your users home directory.
The path depends on the operating system you are using.
On Windows for example, the path could look like this
`C:\Users\<current user name>\.confing\sortier\sortier.json>`.

=== Changing the config

To change anything, you just need to open the file in a text editor.
It doesn't matter which one.
But beforehand, you should know a little bit about JSON itself.
You can find planty of informations here: https://www.json.org/json-en.html

==== The regex part

If you don't know what regex is, you're probably not able to change that part.
Because, if you do something wrong, Sortier won't work anymore.
This regex is the "code" that finds the seasons.

*Normaly, one does not need to change that part.*

==== Any other parts

Other than the regex, you pretty much can change anyting.
Adding languages for example.
As you already know, the file extentions can be changed via a command.
But if you want, you can do it in this file.
Afterwards it still is possible to use the commmand to change it.

[WARNING]
Please do not change the location of the file.
Because Sortier won't work anymore.

